// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuvoPyGEhZqk4SgMxpNyE7_EtfP249sg',
    appId: '1:506208218769:web:434d6c6a49c11af29f9930',
    messagingSenderId: '506208218769',
    projectId: 'movflix-12c2f',
    authDomain: 'movflix-12c2f.firebaseapp.com',
    storageBucket: 'movflix-12c2f.firebasestorage.app',
    measurementId: 'G-Y8NY6S2E2V',
    databaseURL: 'https://movflix-12c2f-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH6310q5MsH_Y60pbBLB-F1WS2aTIFduw',
    appId: '1:506208218769:android:34f44999217f5e4e9f9930',
    messagingSenderId: '506208218769',
    projectId: 'movflix-12c2f',
    storageBucket: 'movflix-12c2f.firebasestorage.app',
    databaseURL: 'https://movflix-12c2f-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAuvoPyGEhZqk4SgMxpNyE7_EtfP249sg',
    appId: '1:506208218769:web:2940d90ab9cccb699f9930',
    messagingSenderId: '506208218769',
    projectId: 'movflix-12c2f',
    authDomain: 'movflix-12c2f.firebaseapp.com',
    storageBucket: 'movflix-12c2f.firebasestorage.app',
    measurementId: 'G-QHEXDKWXNM',
    databaseURL: 'https://movflix-12c2f-default-rtdb.firebaseio.com/',
  );
}
